### PR TITLE
Delete the examples, which are being moved to google3.

### PR DESCRIPTION
**Pull request by dseomn**
These files are being moved to google3 in http://cl/258195375

### CODE REVIEW

**Comment by akefeli** [comment]
There could be authors still referencing these. I'd refrain from deleting them until we have the alternative

**Comment by dseomn** [comment]
> There could be authors still referencing these. I'd refrain from deleting them until we have the alternative

https://critique.corp.google.com/#review/258195375 is in your queue with auto submit enabled, so that's up to you now :)

**Comment by joncass** [comment]
@akefeli @dseomn can you please resolve this PR?

**Comment by akefeli** [comment]
let's keep these here for now, since people still update it. but I believe the future for this repo it should be in g3 and have all the spec markdowns auto generated from schemas.

**Pull request closed without merging**
