### PR TITLE
pass percentage float?

### PR DESCRIPTION
**Pull request by akefeli**
do you guys care if this is float or int. its a float in database and we have been exporting it as float so far.

### CODE REVIEW

**Comment by joncass** [comment]
float is fine with me. though then you should remove two of the dashes on line 390 :)

**Comment by jgan** [comment]
Personally, I don't like it being a float.

With integers it's clear that the whole number represents a percentage.

As a float, it's a little ambiguous between whether 75% is `75` or `.75`. It also adds floating point arithmetic complications for (IMHO) unnecessary levels of precision.

My current opinion is: Let's change the export to cast to integers OR do a brief investigation to see if anyone is using sub-percent precision and change the underlying schema.

In either case, we may want to explicitly say the number must be between 0-100 in this documentation.

**Comment by davetchen** [comment]
My `2.0` cents - leave it as a float to allow for greater precision (5 9's ?), but add documentation to make the range clear

**Comment by eniskonuk** [comment]
I'm w/ @jgan on this one -- unnecessary level of precision that won't be
used and potentially confusing.

Thx
Enis Konuk
Google Cloud Learning
eniskonuk@google.com
+1 617-575-1643

**Comment by akefeli** [comment]
I went with integer everywhere: json schema, db schema, code etc. no more headache from this hopefully

**Pull request closed without merging**
